AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  Environment:
    Type: String

Resources:

  ###########################################################################
  # IMPORTS
  ###########################################################################

  ScanQueueArnParam:
    Type: AWS::SSM::Parameter
    Properties:
      Type: String
      Value: !ImportValue
        Fn::Sub: scan-queue-arn-${Environment}

  ScanQueueUrlParam:
    Type: AWS::SSM::Parameter
    Properties:
      Type: String
      Value: !ImportValue
        Fn::Sub: scan-queue-url-${Environment}

  DriveBucketNameParam:
    Type: AWS::SSM::Parameter
    Properties:
      Type: String
      Value: !ImportValue
        Fn::Sub: drive-bucket-name-${Environment}

  DriveUnscannedBucketNameParam:
    Type: AWS::SSM::Parameter
    Properties:
      Type: String
      Value: !ImportValue
        Fn::Sub: drive-unscanned-bucket-name-${Environment}

  QuarantinedBucketNameParam:
    Type: AWS::SSM::Parameter
    Properties:
      Type: String
      Value: !ImportValue
        Fn::Sub: drive-quarantined-bucket-name-${Environment}

  ScanTableNameParam:
    Type: AWS::SSM::Parameter
    Properties:
      Type: String
      Value: !ImportValue
        Fn::Sub: scan-table-name-${Environment}

  DriveTableNameParam:
    Type: AWS::SSM::Parameter
    Properties:
      Type: String
      Value: !ImportValue
        Fn::Sub: drive-table-name-${Environment}

  ###########################################################################
  # SCAN QUEUE PROCESSOR
  ###########################################################################

  ScanProcessorFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub scanProcessor-${Environment}
      CodeUri: ../../drive/lambda/background-services/
      Handler: scanProcessor.handler
      Runtime: nodejs18.x
      Timeout: 30
      Layers:
        - !ImportValue
          Fn::Sub: aws-sdk-v3-layer-${Environment}
      Environment:
        Variables:
          SCAN_TABLE: !ImportValue
            Fn::Sub: scan-table-name-${Environment}
          DRIVE_TABLE: !ImportValue
            Fn::Sub: drive-table-name-${Environment}
          DRIVE_BUCKET: !ImportValue
            Fn::Sub: drive-bucket-name-${Environment}
          DRIVE_UNSCANNED_BUCKET: !ImportValue
            Fn::Sub: drive-unscanned-bucket-name-${Environment}
          QUARANTINE_BUCKET: !ImportValue
            Fn::Sub: drive-quarantined-bucket-name-${Environment}
      Policies:
        - Statement:
            # read from unscanned bucket, write to drive/quarantine
            - Effect: Allow
              Action:
                - s3:GetObject
              Resource: !Sub arn:aws:s3:::${DriveUnscannedBucketNameParam}/*
            - Effect: Allow
              Action:
                - s3:PutObject
                - s3:DeleteObject
              Resource:
                - !Sub arn:aws:s3:::${DriveBucketNameParam}/*
                - !Sub arn:aws:s3:::${QuarantinedBucketNameParam}/*
            # update scan table + drive table
            - Effect: Allow
              Action:
                - dynamodb:UpdateItem
                - dynamodb:PutItem
                - dynamodb:GetItem
              Resource:
                - !Sub arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${ScanTableNameParam}
                - !Sub arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${DriveTableNameParam}
      Events:
        ScanQueueEvent:
          Type: SQS
          Properties:
            Queue: !ImportValue
              Fn::Sub: scan-queue-arn-${Environment}
            BatchSize: 1

  ###########################################################################
  # QUARANTINE HANDLER (OPTIONAL)
  ###########################################################################

#   QuarantineHandlerFunction:
#     Type: AWS::Serverless::Function
#     Properties:
#       FunctionName: !Sub quarantineHandler-${Environment}
#       CodeUri: ../../lambda/background/quarantineHandler/
#       Handler: index.handler
#       Runtime: nodejs18.x
#       Timeout: 20
#       Layers:
#         - !ImportValue
#           Fn::Sub: aws-sdk-v3-layer-${Environment}
#       Environment:
#         Variables:
#           DRIVE_TABLE: !ImportValue
#             Fn::Sub: drive-table-name-${Environment}
#           QUARANTINE_BUCKET: !ImportValue
#             Fn::Sub: drive-quarantined-bucket-name-${Environment}
#       Policies:
#         - Statement:
#             - Effect: Allow
#               Action:
#                 - s3:GetObject
#                 - s3:DeleteObject
#               Resource: !Sub arn:aws:s3:::${QuarantinedBucketNameParam}/*
#             - Effect: Allow
#               Action:
#                 - dynamodb:UpdateItem
#               Resource: !Sub arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${DriveTableNameParam}

  ###########################################################################
  # CLEANUP HANDLER (IF YOU USE IT)
  ###########################################################################

  CleanupHandlerFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub cleanupHandler-${Environment}
      CodeUri: ../../drive/lambda/background-services/
      Handler: cleanup.handler
      Runtime: nodejs18.x
      Timeout: 20
      Layers:
        - !ImportValue
          Fn::Sub: aws-sdk-v3-layer-${Environment}
      Environment:
        Variables:
          DRIVE_TABLE: !ImportValue
            Fn::Sub: drive-table-name-${Environment}
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - dynamodb:UpdateItem
                - dynamodb:Scan
                - dynamodb:DeleteItem
              Resource: !Sub arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${DriveTableNameParam}

Outputs: {}


