
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  Environment:
    Type: String

Resources:

  DriveUnscannedBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub drive-unscanned-${Environment}-${AWS::AccountId}

      LifecycleConfiguration:
        Rules:
          - Id: CleanupFailedUploads
            Status: Enabled
            Prefix: ''
            ExpirationInDays: 1
            AbortIncompleteMultipartUpload:
              DaysAfterInitiation: 1

      NotificationConfiguration:
        QueueConfigurations:
          - Event: s3:ObjectCreated:*
            Queue: !ImportValue 
              Fn::Sub: "scan-queue-arn-${Environment}"

      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256

  DriveBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub drive-${Environment}-${AWS::AccountId}

      VersioningConfiguration:
        Status: Enabled

      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256

  DriveQuarantinedBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub drive-quarantined-${Environment}-${AWS::AccountId}

      LifecycleConfiguration:
        Rules:
          - Id: QuarantineCleanup
            Status: Enabled
            Prefix: ''
            ExpirationInDays: 5

      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256

Outputs:

  DriveUnscannedBucketName:
    Value: !Ref DriveUnscannedBucket
    Export:
      Name: !Sub "drive-unscanned-bucket-name-${Environment}"

  DriveBucketName:
    Value: !Ref DriveBucket
    Export:
      Name: !Sub "drive-bucket-name-${Environment}"

  DriveQuarantinedBucketName:
    Value: !Ref DriveQuarantinedBucket
    Export:
      Name: !Sub "drive-quarantined-bucket-name-${Environment}"