
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  Environment:
    Type: String

Resources:

  UserSettingsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub user-settings-${Environment}
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: user_id
          AttributeType: S
        - AttributeName: plan_type
          AttributeType: S
        - AttributeName: quota_reset_at
          AttributeType: N
      KeySchema:
        - AttributeName: user_id
          KeyType: HASH
      TimeToLiveSpecification:
        AttributeName: quota_reset_at
        Enabled: true
      GlobalSecondaryIndexes:
        - IndexName: PlanTypeIndex
          KeySchema:
            - AttributeName: plan_type
              KeyType: HASH
          Projection:
            ProjectionType: ALL
        - IndexName: QuotaResetIndex
          KeySchema:
            - AttributeName: quota_reset_at
              KeyType: HASH
          Projection:
            ProjectionType: KEYS_ONLY

  DriveTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub drive-table-${Environment}
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: user_id
          AttributeType: S
        - AttributeName: file_id
          AttributeType: S
        - AttributeName: folder_id
          AttributeType: S
        - AttributeName: last_accessed
          AttributeType: N
        - AttributeName: trashed
          AttributeType: N
      KeySchema:
        - AttributeName: user_id
          KeyType: HASH
        - AttributeName: file_id
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: UserFolderIndex
          KeySchema:
            - AttributeName: user_id
              KeyType: HASH
            - AttributeName: folder_id
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: UserLastAccessedIndex
          KeySchema:
            - AttributeName: user_id
              KeyType: HASH
            - AttributeName: last_accessed
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: TrashIndex
          KeySchema:
            - AttributeName: trashed
              KeyType: HASH
            - AttributeName: last_accessed
              KeyType: RANGE
          Projection:
            ProjectionType: ALL

  ScanTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub scan-table-${Environment}
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: user_id
          AttributeType: S
        - AttributeName: file_id
          AttributeType: S
        - AttributeName: scan_status
          AttributeType: S
      KeySchema:
        - AttributeName: user_id
          KeyType: HASH
        - AttributeName: file_id
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: ScanStatusIndex
          KeySchema:
            - AttributeName: scan_status
              KeyType: HASH
          Projection:
            ProjectionType: ALL

  ShareTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub share-table-${Environment}
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: share_id
          AttributeType: S
      KeySchema:
        - AttributeName: share_id
          KeyType: HASH
      TimeToLiveSpecification:
        AttributeName: expires_at
        Enabled: true

Outputs:

  UserSettingsTableName:
    Value: !Ref UserSettingsTable
    Export:
      Name: !Sub user-settings-table-name-${Environment}

  DriveTableName:
    Value: !Ref DriveTable
    Export:
      Name: !Sub drive-table-name-${Environment}

  ScanTableName:
    Value: !Ref ScanTable
    Export:
      Name: !Sub scan-table-name-${Environment}

  ShareTableName:
    Value: !Ref ShareTable
    Export:
      Name: !Sub share-table-name-${Environment}

