AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Drive Lambdas (modular)

Parameters:
  Environment:
    Type: String

Resources:

  ###########################################################################
  # DRIVE — S3 PRESIGNED URL FUNCTIONS
  ###########################################################################

  GetPresignedUrlFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "getPresignedUrl-${Environment}"
      CodeUri: ../../drive/lambda/getPresignedUrl/
      Handler: getPresignedUrl.handler
      Runtime: nodejs22.x
      Layers:
        - !ImportValue 
          Fn::Sub: "aws-sdk-v3-layer-${Environment}"
      Policies:
        - Statement:
            - Sid: AllowUploadOnlyToUnscannedBucket
              Effect: Allow
              Action:
                - s3:PutObject
              Resource: !Sub 
                - "arn:aws:s3:::${BucketName}/*"
                - BucketName: !ImportValue 
                    Fn::Sub: "drive-unscanned-bucket-name-${Environment}"

            - Sid: AllowDownloadOnlyFromDriveBucket
              Effect: Allow
              Action:
                - s3:GetObject
              Resource: !Sub 
                - "arn:aws:s3:::${BucketName}/*"
                - BucketName: !ImportValue 
                    Fn::Sub: "drive-bucket-name-${Environment}"

            - Sid: AllowReadUserSettings
              Effect: Allow
              Action:
                - dynamodb:GetItem
                - dynamodb:Query
              Resource: !Sub 
                - "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${TableName}"
                - TableName: !ImportValue 
                    Fn::Sub: "user-settings-table-name-${Environment}"

      Environment:
        Variables:
          DRIVE_UNSCANNED_BUCKET: !ImportValue 
            Fn::Sub: "drive-unscanned-bucket-name-${Environment}"
          DRIVE_BUCKET: !ImportValue 
            Fn::Sub: "drive-bucket-name-${Environment}"
          USER_SETTINGS_TABLE: !ImportValue 
            Fn::Sub: "user-settings-table-name-${Environment}"
      Events:
        PresignedUrl:
          Type: Api
          Properties:
            Path: /drive/pre-signed/transmit
            Method: POST

  PresignedUrlShareFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "presignedUrlShare-${Environment}"
      CodeUri: ../../drive/lambda/getPresignedUrl/
      Handler: presignedUrlShare.handler
      Runtime: nodejs22.x
      Layers:
        - !ImportValue 
          Fn::Sub: "aws-sdk-v3-layer-${Environment}"
      Policies:
        - Statement:
            - Sid: AllowGetObjectFromDriveBucket
              Effect: Allow
              Action:
                - s3:GetObject
              Resource: !Sub 
                - "arn:aws:s3:::${BucketName}/*"
                - BucketName: !ImportValue 
                    Fn::Sub: "drive-bucket-name-${Environment}"

            - Sid: AllowPutAndGetItemInShareTable
              Effect: Allow
              Action:
                - dynamodb:PutItem
                - dynamodb:GetItem
              Resource: !Sub 
                - "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${TableName}"
                - TableName: !ImportValue 
                    Fn::Sub: "share-table-name-${Environment}"

            - Sid: AllowReadAndUpdateUserSettings
              Effect: Allow
              Action:
                - dynamodb:GetItem
                - dynamodb:UpdateItem
              Resource: !Sub 
                - "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${TableName}"
                - TableName: !ImportValue 
                    Fn::Sub: "user-settings-table-name-${Environment}"

      Environment:
        Variables:
          DRIVE_BUCKET: !ImportValue 
            Fn::Sub: "drive-bucket-name-${Environment}"
          SHARE_TABLE: !ImportValue 
            Fn::Sub: "share-table-name-${Environment}"
          USER_SETTINGS_TABLE: !ImportValue 
            Fn::Sub: "user-settings-table-name-${Environment}"
      Events:
        ShareUrl:
          Type: Api
          Properties:
            Path: /drive/pre-signed/share
            Method: POST

  ###########################################################################
  # DRIVE — FILE SERVICES
  ###########################################################################

  ListFilesFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "listFiles-${Environment}"
      CodeUri: ../../drive/lambda/file-services/
      Handler: listFiles.handler
      Runtime: nodejs22.x
      Policies:
        - DynamoDBReadPolicy:
            TableName: !ImportValue 
              Fn::Sub: "drive-table-name-${Environment}"
        - Statement:
            - Effect: Allow
              Action:
                - dynamodb:GetItem
              Resource: !Sub 
                - "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${TableName}"
                - TableName: !ImportValue 
                    Fn::Sub: "user-settings-table-name-${Environment}"
      Environment:
        Variables:
          DRIVE_TABLE: !ImportValue 
            Fn::Sub: "drive-table-name-${Environment}"
          USER_SETTINGS_TABLE: !ImportValue 
            Fn::Sub: "user-settings-table-name-${Environment}"
      Events:
        ListFiles:
          Type: Api
          Properties:
            Path: /drive/file-service/listFiles
            Method: GET

  MoveFileFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "moveFile-${Environment}"
      CodeUri: ../../drive/lambda/file-services/
      Handler: moveFile.handler
      Runtime: nodejs22.x
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - s3:PutObject
                - s3:DeleteObject
                - s3:GetObject
              Resource: !Sub 
                - "arn:aws:s3:::${BucketName}/*"
                - BucketName: !ImportValue 
                    Fn::Sub: "drive-bucket-name-${Environment}"
        - Statement:
            - Effect: Allow
              Action:
                - dynamodb:UpdateItem
                - dynamodb:GetItem
              Resource: !Sub 
                - "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${TableName}"
                - TableName: !ImportValue 
                    Fn::Sub: "drive-table-name-${Environment}"
      Environment:
        Variables:
          DRIVE_BUCKET: !ImportValue 
            Fn::Sub: "drive-bucket-name-${Environment}"
          DRIVE_TABLE: !ImportValue 
            Fn::Sub: "drive-table-name-${Environment}"
      Events:
        MoveFile:
          Type: Api
          Properties:
            Path: /drive/file-services/{id}/move
            Method: PATCH

  DeleteFileFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "DeleteFile-${Environment}"
      CodeUri: ../../drive/lambda/file-services/
      Handler: softdeleteFile.handler
      Runtime: nodejs22.x
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - s3:DeleteObject
              Resource: !Sub 
                - "arn:aws:s3:::${BucketName}/*"
                - BucketName: !ImportValue 
                    Fn::Sub: "drive-bucket-name-${Environment}"
        - Statement:
            - Effect: Allow
              Action:
                - dynamodb:UpdateItem
              Resource: !Sub 
                - "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${TableName}"
                - TableName: !ImportValue 
                    Fn::Sub: "drive-table-name-${Environment}"
      Environment:
        Variables:
          DRIVE_BUCKET: !ImportValue 
            Fn::Sub: "drive-bucket-name-${Environment}"
          DRIVE_TABLE: !ImportValue 
            Fn::Sub: "drive-table-name-${Environment}"
      Events:
        SoftDelete:
          Type: Api
          Properties:
            Path: /drive/file-services/{id}/soft-delete
            Method: DELETE

  RestoreFileFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "restoreFile-${Environment}"
      CodeUri: ../../drive/lambda/file-services/
      Handler: restoreFile.handler
      Runtime: nodejs22.x
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - s3:ListObjectVersions
                - s3:DeleteObjectVersion
              Resource: !Sub 
                - "arn:aws:s3:::${BucketName}/*"
                - BucketName: !ImportValue 
                    Fn::Sub: "drive-bucket-name-${Environment}"
        - Statement:
            - Effect: Allow
              Action:
                - dynamodb:UpdateItem
              Resource: !Sub 
                - "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${TableName}"
                - TableName: !ImportValue 
                    Fn::Sub: "drive-table-name-${Environment}"
      Environment:
        Variables:
          DRIVE_BUCKET: !ImportValue 
            Fn::Sub: "drive-bucket-name-${Environment}"
          DRIVE_TABLE: !ImportValue 
            Fn::Sub: "drive-table-name-${Environment}"
      Events:
        RestoreFile:
          Type: Api
          Properties:
            Path: /drive/file-services/{id}/restore
            Method: POST

  ###########################################################################
  # DRIVE — FILE RECORD OPERATIONS
  ###########################################################################

  CreateFileRecordFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "createFileRecord-${Environment}"
      CodeUri: ../../drive/lambda/file-records/
      Handler: createFileRecord.handler
      Runtime: nodejs22.x
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - dynamodb:PutItem
              Resource:
                - !Sub 
                  - "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${TableName}"
                  - TableName: !ImportValue 
                      Fn::Sub: "drive-table-name-${Environment}"
                - !Sub 
                  - "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${TableName}"
                  - TableName: !ImportValue 
                      Fn::Sub: "scan-table-name-${Environment}"
                - !Sub 
                  - "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${TableName}"
                  - TableName: !ImportValue 
                      Fn::Sub: "share-table-name-${Environment}"
      Environment:
        Variables:
          SCAN_TABLE: !ImportValue 
            Fn::Sub: "scan-table-name-${Environment}"
          DRIVE_TABLE: !ImportValue 
            Fn::Sub: "drive-table-name-${Environment}"
          SHARE_TABLE: !ImportValue 
            Fn::Sub: "share-table-name-${Environment}"
      Events:
        CreateFile:
          Type: Api
          Properties:
            Path: /drive/file-records/createFileRecord
            Method: POST

  UpdateFileRecordFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "updateFileRecord-${Environment}"
      CodeUri: ../../drive/lambda/file-records/
      Handler: updateFileRecord.handler
      Runtime: nodejs22.x
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - dynamodb:UpdateItem
              Resource:
                - !Sub 
                  - "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${TableName}"
                  - TableName: !ImportValue 
                      Fn::Sub: "drive-table-name-${Environment}"
                - !Sub 
                  - "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${TableName}"
                  - TableName: !ImportValue 
                      Fn::Sub: "scan-table-name-${Environment}"
                - !Sub 
                  - "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${TableName}"
                  - TableName: !ImportValue 
                      Fn::Sub: "share-table-name-${Environment}"
      Environment:
        Variables:
          SCAN_TABLE: !ImportValue 
            Fn::Sub: "scan-table-name-${Environment}"
          DRIVE_TABLE: !ImportValue 
            Fn::Sub: "drive-table-name-${Environment}"
          SHARE_TABLE: !ImportValue 
            Fn::Sub: "share-table-name-${Environment}"
      Events:
        UpdateFile:
          Type: Api
          Properties:
            Path: /drive/file-records/updateFileRecord/{id}
            Method: PATCH

  DeleteFileRecordFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "deleteFileRecord-${Environment}"
      CodeUri: ../../drive/lambda/file-records/
      Handler: deleteFileRecord.handler
      Runtime: nodejs22.x
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - dynamodb:DeleteItem
              Resource:
                - !Sub 
                  - "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${TableName}"
                  - TableName: !ImportValue 
                      Fn::Sub: "drive-table-name-${Environment}"
                - !Sub 
                  - "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${TableName}"
                  - TableName: !ImportValue 
                      Fn::Sub: "scan-table-name-${Environment}"
                - !Sub 
                  - "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${TableName}"
                  - TableName: !ImportValue 
                      Fn::Sub: "share-table-name-${Environment}"
      Environment:
        Variables:
          SCAN_TABLE: !ImportValue 
            Fn::Sub: "scan-table-name-${Environment}"
          DRIVE_TABLE: !ImportValue 
            Fn::Sub: "drive-table-name-${Environment}"
          SHARE_TABLE: !ImportValue 
            Fn::Sub: "share-table-name-${Environment}"
      Events:
        DeleteFile:
          Type: Api
          Properties:
            Path: /drive/file-records/deleteFileRecord/{id}
            Method: DELETE

  GetFileRecordFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "getFileRecord-${Environment}"
      CodeUri: ../../drive/lambda/file-records/
      Handler: getFileRecord.handler
      Runtime: nodejs22.x
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - dynamodb:GetItem
                - dynamodb:Query
                - dynamodb:Scan
              Resource:
                - !Sub 
                  - "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${TableName}"
                  - TableName: !ImportValue 
                      Fn::Sub: "drive-table-name-${Environment}"
                - !Sub 
                  - "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${TableName}"
                  - TableName: !ImportValue 
                      Fn::Sub: "scan-table-name-${Environment}"
                - !Sub 
                  - "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${TableName}"
                  - TableName: !ImportValue 
                      Fn::Sub: "share-table-name-${Environment}"
      Environment:
        Variables:
          SCAN_TABLE: !ImportValue 
            Fn::Sub: "scan-table-name-${Environment}"
          DRIVE_TABLE: !ImportValue 
            Fn::Sub: "drive-table-name-${Environment}"
          SHARE_TABLE: !ImportValue 
            Fn::Sub: "share-table-name-${Environment}"
      Events:
        FileInfo:
          Type: Api
          Properties:
            Path: /drive/file-records/getFileRecord/{id}
            Method: GET