AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Drive Lambdas (modular)

Parameters:
  Environment:
    Type: String

Resources:

  ###########################################################################
  # DRIVE — S3 PRESIGNED URL FUNCTIONS
  ###########################################################################

  GetPresignedUrlFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub getPresignedUrl-${Environment}
      CodeUri: ../../drive/lambda/getPresignedUrl/
      Handler: getPresignedUrl.handler
      Runtime: nodejs18.x
      Layers:
        - !ImportValue
            Fn::Sub: aws-sdk-v3-layer-${Environment}
      Policies:
        - Statement:
            - Sid: AllowUploadOnlyToUnscannedBucket
              Effect: Allow
              Action:
                - s3:PutObject
              Resource: !ImportValue
                Fn::Sub: drive-unscanned-bucket-arn-${Environment}

            - Sid: AllowDownloadOnlyFromDriveBucket
              Effect: Allow
              Action:
                - s3:GetObject
              Resource: !ImportValue
                Fn::Sub: drive-bucket-arn-${Environment}

            - Sid: AllowReadUserSettings
              Effect: Allow
              Action:
                - dynamodb:GetItem
                - dynamodb:Query
              Resource: !ImportValue
                Fn::Sub: user-settings-table-arn-${Environment}

      Environment:
        Variables:
          DRIVE_UNSCANNED_BUCKET: !ImportValue
            Fn::Sub: drive-unscanned-bucket-name-${Environment}
          DRIVE_BUCKET: !ImportValue
            Fn::Sub: drive-bucket-name-${Environment}
          USER_SETTINGS_TABLE: !ImportValue
            Fn::Sub: user-settings-table-name-${Environment}
      Events:
        PresignedUrl:
          Type: Api
          Properties:
            Path: /drive/pre-signed/transmit
            Method: POST

  PresignedUrlShareFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub presignedUrlShare-${Environment}
      CodeUri: ../../drive/lambda/getPresignedUrl/
      Handler: presignedUrlShare.handler
      Runtime: nodejs18.x
      Layers:
        - !ImportValue
            Fn::Sub: aws-sdk-v3-layer-${Environment}
      Policies:
        - Statement:
            - Sid: AllowGetObjectFromDriveBucket
              Effect: Allow
              Action:
                - s3:GetObject
              Resource: !ImportValue
                Fn::Sub: drive-bucket-arn-${Environment}

            - Sid: AllowPutAndGetItemInShareTable
              Effect: Allow
              Action:
                - dynamodb:PutItem
                - dynamodb:GetItem
              Resource: !ImportValue
                Fn::Sub: share-table-arn-${Environment}

            - Sid: AllowReadAndUpdateUserSettings
              Effect: Allow
              Action:
                - dynamodb:GetItem
                - dynamodb:UpdateItem
              Resource: !ImportValue
                Fn::Sub: user-settings-table-arn-${Environment}

      Environment:
        Variables:
          DRIVE_BUCKET: !ImportValue
            Fn::Sub: drive-bucket-name-${Environment}
          SHARE_TABLE: !ImportValue
            Fn::Sub: share-table-name-${Environment}
          USER_SETTINGS_TABLE: !ImportValue
            Fn::Sub: user-settings-table-name-${Environment}
      Events:
        ShareUrl:
          Type: Api
          Properties:
            Path: /drive/pre-signed/share
            Method: POST

  ###########################################################################
  # DRIVE — FILE SERVICES
  ###########################################################################

  ListFilesFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub listFiles-${Environment}
      CodeUri: ../../drive/lambda/file-services/
      Handler: listFiles.handler
      Runtime: nodejs18.x
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - dynamodb:Query
              Resource:
                - !ImportValue
                    Fn::Sub: drive-table-arn-${Environment}
                - !Sub ${!ImportValue Fn::Sub: drive-table-arn-${Environment}}/index/UserLastAccessedIndex
                - !Sub ${!ImportValue Fn::Sub: drive-table-arn-${Environment}}/index/UserFolderIndex
                - !Sub ${!ImportValue Fn::Sub: drive-table-arn-${Environment}}/index/TrashIndex
        - Statement:
            - Effect: Allow
              Action:
                - dynamodb:GetItem
              Resource: !ImportValue
                Fn::Sub: user-settings-table-arn-${Environment}
      Environment:
        Variables:
          DRIVE_TABLE: !ImportValue
            Fn::Sub: drive-table-name-${Environment}
          USER_SETTINGS_TABLE: !ImportValue
            Fn::Sub: user-settings-table-name-${Environment}
      Events:
        ListFiles:
          Type: Api
          Properties:
            Path: /drive/file-service/listFiles
            Method: GET

  MoveFileFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub moveFile-${Environment}
      CodeUri: ../../drive/lambda/file-services/
      Handler: moveFile.handler
      Runtime: nodejs18.x
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - s3:PutObject
                - s3:DeleteObject
                - s3:GetObject
              Resource: !ImportValue
                Fn::Sub: drive-bucket-arn-${Environment}
        - Statement:
            - Effect: Allow
              Action:
                - dynamodb:UpdateItem
                - dynamodb:GetItem
              Resource: !ImportValue
                Fn::Sub: drive-table-arn-${Environment}
      Environment:
        Variables:
          DRIVE_BUCKET: !ImportValue
            Fn::Sub: drive-bucket-name-${Environment}
          DRIVE_TABLE: !ImportValue
            Fn::Sub: drive-table-name-${Environment}
      Events:
        MoveFile:
          Type: Api
          Properties:
            Path: /drive/file-services/{id}/move
            Method: PATCH

  DeleteFileFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub DeleteFile-${Environment}
      CodeUri: ../../drive/lambda/file-services/
      Handler: softdeleteFile.handler
      Runtime: nodejs18.x
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - s3:DeleteObject
              Resource: !ImportValue
                Fn::Sub: drive-bucket-arn-${Environment}
        - Statement:
            - Effect: Allow
              Action:
                - dynamodb:UpdateItem
              Resource: !ImportValue
                Fn::Sub: drive-table-arn-${Environment}
      Environment:
        Variables:
          DRIVE_BUCKET: !ImportValue
            Fn::Sub: drive-bucket-name-${Environment}
          DRIVE_TABLE: !ImportValue
            Fn::Sub: drive-table-name-${Environment}
      Events:
        SoftDelete:
          Type: Api
          Properties:
            Path: /drive/file-services/{id}/soft-delete
            Method: DELETE

  RestoreFileFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub restoreFile-${Environment}
      CodeUri: ../../drive/lambda/file-services/
      Handler: restoreFile.handler
      Runtime: nodejs18.x
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - s3:ListObjectVersions
                - s3:DeleteObjectVersion
              Resource: !ImportValue
                Fn::Sub: drive-bucket-arn-${Environment}
        - Statement:
            - Effect: Allow
              Action:
                - dynamodb:UpdateItem
              Resource: !ImportValue
                Fn::Sub: drive-table-arn-${Environment}
      Environment:
        Variables:
          DRIVE_BUCKET: !ImportValue
            Fn::Sub: drive-bucket-name-${Environment}
          DRIVE_TABLE: !ImportValue
            Fn::Sub: drive-table-name-${Environment}
      Events:
        RestoreFile:
          Type: Api
          Properties:
            Path: /drive/file-services/{id}/restore
            Method: POST

  ###########################################################################
  # DRIVE — FILE RECORD OPERATIONS
  ###########################################################################

  CreateFileRecordFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub createFileRecord-${Environment}
      CodeUri: ../../drive/lambda/file-records/
      Handler: createFileRecord.handler
      Runtime: nodejs18.x
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - dynamodb:PutItem
              Resource:
                - !ImportValue
                    Fn::Sub: drive-table-arn-${Environment}
                - !ImportValue
                    Fn::Sub: scan-table-arn-${Environment}
                - !ImportValue
                    Fn::Sub: share-table-arn-${Environment}
      Environment:
        Variables:
          SCAN_TABLE: !ImportValue
            Fn::Sub: scan-table-name-${Environment}
          DRIVE_TABLE: !ImportValue
            Fn::Sub: drive-table-name-${Environment}
          SHARE_TABLE: !ImportValue
            Fn::Sub: share-table-name-${Environment}
      Events:
        CreateFile:
          Type: Api
          Properties:
            Path: /drive/file-records/createFileRecord
            Method: POST
  UpdateFileRecordFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub updateFileRecord-${Environment}
      CodeUri: ../../drive/lambda/file-records/
      Handler: updateFileRecord.handler
      Runtime: nodejs18.x
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - dynamodb:UpdateItem
              Resource:
                - !ImportValue
                    Fn::Sub: drive-table-arn-${Environment}
                - !ImportValue
                    Fn::Sub: scan-table-arn-${Environment}
                - !ImportValue
                    Fn::Sub: share-table-arn-${Environment}
      Environment:
        Variables:
          SCAN_TABLE: !ImportValue
            Fn::Sub: scan-table-name-${Environment}
          DRIVE_TABLE: !ImportValue
            Fn::Sub: drive-table-name-${Environment}
          SHARE_TABLE: !ImportValue
            Fn::Sub: share-table-name-${Environment}
      Events:
        UpdateFile:
          Type: Api
          Properties:
            Path: /drive/file-records/updateFileRecord/{id}
            Method: PATCH

  DeleteFileRecordFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub deleteFileRecord-${Environment}
      CodeUri: ../../drive/lambda/file-records/
      Handler: deleteFileRecord.handler
      Runtime: nodejs18.x
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - dynamodb:DeleteItem
              Resource:
                - !ImportValue
                    Fn::Sub: drive-table-arn-${Environment}
                - !ImportValue
                    Fn::Sub: scan-table-arn-${Environment}
                - !ImportValue
                    Fn::Sub: share-table-arn-${Environment}
      Environment:
        Variables:
          SCAN_TABLE: !ImportValue
            Fn::Sub: scan-table-name-${Environment}
          DRIVE_TABLE: !ImportValue
            Fn::Sub: drive-table-name-${Environment}
          SHARE_TABLE: !ImportValue
            Fn::Sub: share-table-name-${Environment}
      Events:
        DeleteFile:
          Type: Api
          Properties:
            Path: /drive/file-records/deleteFileRecord/{id}
            Method: DELETE

  GetFileRecordFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub getFileRecord-${Environment}
      CodeUri: ../../drive/lambda/file-records/
      Handler: getFileRecord.handler
      Runtime: nodejs18.x
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - dynamodb:GetItem
                - dynamodb:Query
                - dynamodb:Scan
              Resource:
                - !ImportValue
                    Fn::Sub: drive-table-arn-${Environment}
                - !ImportValue
                    Fn::Sub: scan-table-arn-${Environment}
                - !ImportValue
                    Fn::Sub: share-table-arn-${Environment}
      Environment:
        Variables:
          SCAN_TABLE: !ImportValue
            Fn::Sub: scan-table-name-${Environment}
          DRIVE_TABLE: !ImportValue
            Fn::Sub: drive-table-name-${Environment}
          SHARE_TABLE: !ImportValue
            Fn::Sub: share-table-name-${Environment}
      Events:
        FileInfo:
          Type: Api
          Properties:
            Path: /drive/file-records/getFileRecord/{id}
            Method: GET
