AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Backend Drive Storage API with Virus Scanning

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues: [dev, staging, prod]

Resources:
  # S3 Buckets
  DriveUnscannedBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub drive-unscanned-${Environment}-${AWS::AccountId}
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          - Id: CleanupFailedUploads
            Status: Enabled
            Prefix: ""
            ExpirationInDays: 1
            AbortIncompleteMultipartUpload:
              DaysAfterInitiation: 1

  DriveBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub drive-${Environment}-${AWS::AccountId}
      VersioningConfiguration:
        Status: Enabled

  DriveQuarantinedBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub drive-quarantined-${Environment}-${AWS::AccountId}
      VersioningConfiguration:
        Status: Enabled

  # DynamoDB Tables
  DriveTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub drive-table-${Environment}
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: user_id
          AttributeType: S
        - AttributeName: file_id
          AttributeType: S
        - AttributeName: last_accessed
          AttributeType: N
        - AttributeName: folder_id
          AttributeType: S
        - AttributeName: trashed
          AttributeType: N
      KeySchema:
        - AttributeName: user_id
          KeyType: HASH
        - AttributeName: file_id
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: UserLastAccessedIndex
          KeySchema:
            - AttributeName: user_id
              KeyType: HASH
            - AttributeName: last_accessed
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: UserFolderIndex
          KeySchema:
            - AttributeName: user_id
              KeyType: HASH
            - AttributeName: folder_id
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: TrashIndex
          KeySchema:
            - AttributeName: trashed
              KeyType: HASH
          Projection:
            ProjectionType: ALL

  ScanTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub scan-table-${Environment}
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: user_id
          AttributeType: S
        - AttributeName: file_id
          AttributeType: S
        - AttributeName: scan_status
          AttributeType: S
      KeySchema:
        - AttributeName: user_id
          KeyType: HASH
        - AttributeName: file_id
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: ScanStatusIndex
          KeySchema:
            - AttributeName: scan_status
              KeyType: HASH
          Projection:
            ProjectionType: ALL

  ShareTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub share-table-${Environment}
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: share_id
          AttributeType: S
        - AttributeName: expires_at
          AttributeType: N
      KeySchema:
        - AttributeName: share_id
          KeyType: HASH
      TimeToLiveSpecification:
        AttributeName: expires_at
        Enabled: true

  # SQS Queue for Scanning
  ScanQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub file-scan-queue-${Environment}
      VisibilityTimeout: 900
      RedrivePolicy:
        deadLetterTargetArn: !GetRef ScanQueueDLQ
        maxReceiveCount: 3

  ScanQueueDLQ:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub file-scan-queue-dlq-${Environment}


  # Lambda Functions
  GetPresignedUrlFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub getPresignedUrl-${Environment}
      CodeUri: lambda/getPresignedUrl/ #change code uri
      Handler: index.handler
      Runtime: nodejs18.x
      Layers:
        - !Ref AwsSdkV3Layer
      Policies:
        - Statement:
            - Sid: AllowUploadOnlyToUnscannedBucket
              Effect: Allow
              Action:
                - s3:PutObject
              Resource: !Sub arn:aws:s3:::${DriveUnscannedBucket}/*

            - Sid: AllowDownloadOnlyFromDriveBucket
              Effect: Allow
              Action:
                - s3:GetObject
              Resource: !Sub arn:aws:s3:::${DriveBucket}/*
      Environment:
        Variables:
          DRIVE_UNSCANNED_BUCKET: !Ref DriveUnscannedBucket
          DRIVE_BUCKET: !Ref DriveBucket
      Events:
        PresignedUrl:
          Type: Api
          Properties:
            Path: /drive/pre-signed/transmit
            Method: POST

  PresignedUrlShareFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub presignedUrlShare-${Environment}
      CodeUri: lambda/presignedUrlShare/ #change code uri
      Handler: index.handler
      Runtime: nodejs18.x
      Policies:
       - Statement:
          - Sid: AllowGetObjectFromDriveBucket
            Effect: Allow
            Action:
              - s3:GetObject
            Resource: !Sub arn:aws:s3:::${DriveBucket}/*
          
          - Sid: AllowPutAndGetItemInShareTable
            Effect: Allow
            Action:
              - dynamodb:PutItem
              - dynamodb:GetItem
            Resource: !GetAtt ShareTable.Arn

          - Sid: AllowReadAndUpdateUserSettings
            Effect: Allow
            Action:
              - dynamodb:GetItem
              - dynamodb:UpdateItem
            Resource: !GetAtt UserSettingsTable.Arn 


      Environment:
        Variables:
          DRIVE_BUCKET: !Ref DriveBucket
          SHARE_TABLE: !Ref ShareTable
          USER_SETTINGS_TABLE: !Ref UserSettingsTable
          
      Events:
        ShareUrl:
          Type: Api
          Properties:
            Path: /drive/pre-signed/share
            Method: POST

 
  ListFilesFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub listFiles-${Environment}
      CodeUri: lambda/listFiles/ #change code uri
      Handler: index.handler
      Runtime: nodejs18.x
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - dynamodb:Query
              Resource:
                - !GetAtt DriveTable.Arn
                - !Sub ${DriveTable.Arn}/index/UserLastAccessedIndex
                - !Sub ${DriveTable.Arn}/index/UserFolderIndex
                - !Sub ${DriveTable.Arn}/index/TrashIndex

      Environment:
        Variables:
          DRIVE_TABLE: !Ref DriveTable
      Events:
        ListFiles:
          Type: Api
          Properties:
            Path: /drive/file-services/listFiles
            Method: GET


# functions handling file record operations in DynamoDB


  CreateFileRecordFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub createFileRecord-${Environment}
      CodeUri: lambda/createFileRecord/
      Handler: index.handler  #change
      Runtime: nodejs18.x
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - dynamodb:PutItem
              Resource:
                - !GetAtt DriveTable.Arn
                - !GetAtt ScanTable.Arn
                - !GetAtt ShareTable.Arn

      Environment:
        Variables:
          SCAN_TABLE: !Ref ScanTable
          DRIVE_TABLE: !Ref DriveTable
          SHARE_TABLE: !Ref ShareTable
      Events:
        CreateFile:
          Type: Api
          Properties:
            Path: /drive/file-services/createFileRecord
            Method: POST



  UpdateFileRecordFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub updateFileRecord-${Environment}
      CodeUri: lambda/updateFileRecord/
      Handler: index.handler
      Runtime: nodejs18.x
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - dynamodb:UpdateItem   #updating file records
              Resource:
                - !GetAtt DriveTable.Arn
                - !GetAtt ScanTable.Arn
                - !GetAtt ShareTable.Arn

      Environment:
        Variables:
          SCAN_TABLE: !Ref ScanTable
          DRIVE_TABLE: !Ref DriveTable
          SHARE_TABLE: !Ref ShareTable
      Events:
        UpdateFile:
          Type: Api
          Properties:
            Path: /drive/file-services/updateFileRecord/{id}
            Method: PATCH


  DeleteFileRecordFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub deleteFileRecord-${Environment}
      CodeUri: lambda/deleteFileRecord/
      Handler: index.handler  #change
      Runtime: nodejs18.x
      Policies:
        - Statement:
            - Effect: Allow
              Action:
               - dynamodb:DeleteItem
              Resource:
                - !GetAtt DriveTable.Arn
                - !GetAtt ScanTable.Arn
                - !GetAtt ShareTable.Arn

      Environment:
        Variables:
          SCAN_TABLE: !Ref ScanTable
          DRIVE_TABLE: !Ref DriveTable
          SHARE_TABLE: !Ref ShareTable
      Events:
        DeleteFile:
          Type: Api
          Properties:
            Path: /drive/file-services/deleteFileRecord/{id}
            Method: DELETE

  GetFileRecordFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub getFileRecord-${Environment}
      CodeUri: lambda/getFileRecord/ #change code uri
      Handler: index.handler
      Runtime: nodejs18.x
      Policies:
        - Statement:
            - Effect: Allow
              Action:
              - dynamodb:GetItem
              - dynamodb:Query
              - dynamodb:Scan
              Resource:
                - !GetAtt DriveTable.Arn
                - !GetAtt ScanTable.Arn
                - !GetAtt ShareTable.Arn

      Environment:
        Variables:
          SCAN_TABLE: !Ref ScanTable
          DRIVE_TABLE: !Ref DriveTable
          SHARE_TABLE: !Ref ShareTable

      Events:
        FileInfo:
          Type: Api
          Properties:
            Path: /drive/file-services/getFileRecord/{id}
            Method: GET



##### where i am 

  MoveFileFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub moveFile-${Environment}
      CodeUri: lambda/moveFile/
      Handler: index.handler
      Runtime: nodejs18.x
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - s3:PutObject       # needed to upload or copy objects into a bucket
                - s3:DeleteObject    # needed to remove the original object
                - s3:GetObject  
              Resource: !Sub "${DriveBucket.Arn}/*"
            - Effect: Allow
              Action:
                - dynamodb:UpdateItem
                - dynamodb:GetItem
              Resource:  !Sub "${DriveBucket.Arn}/*"
      Environment:
        Variables:
          DRIVE_BUCKET: !Ref DriveBucket
          DRIVE_TABLE: !Ref DriveTable
      Events:
        MoveFile:
          Type: Api
          Properties:
            Path: /drive/file-services/{id}/move
            Method: PATCH

  # CopyFileFunction:
  #   Type: AWS::Serverless::Function
  #   Properties:
  #     FunctionName: !Sub copyFile-${Environment}
  #     CodeUri: lambda/copyFile/
  #     Handler: index.handler
  #     Runtime: nodejs18.x
  #     Policies:
  #       - Statement:
  #           - Effect: Allow
  #             Action:
  #               - s3:PutObject       # needed to upload or copy objects into a bucket
  #               - s3:GetObject  
  #             Resource:
  #               - !GetAtt DriveBucket.Arn     
  #           - Effect: Allow
  #             Action:
  #               - dynamodb:PutItem
  #               - dynamodb:GetItem
  #             Resource: !GetAtt DriveTable.Arn     

  #     Environment:
  #       Variables:
  #         DRIVE_BUCKET: !Ref DriveBucket
  #         DRIVE_TABLE: !Ref DriveTable
  #     Events:
  #       CopyFile:
  #         Type: Api
  #         Properties:
  #           Path: /drive/file-services/{id}/copy
  #           Method: POST


  DeleteFileFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub DeleteFile-${Environment}
      CodeUri: lambda/DeleteFile/
      Handler: index.handler
      Runtime: nodejs18.x
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - s3:DeleteObject    # needed to remove the original object
              Resource:
                - !Sub "${DriveBucket.Arn}/*"
            - Effect: Allow
              Action:
                - dynamodb:UpdateItem
              Resource: !GetAtt DriveTable.Arn

      Environment:
        Variables:
          DRIVE_BUCKET: !Ref DriveBucket
          DRIVE_TABLE: !Ref DriveTable
      Events:
        SoftDelete:
          Type: Api
          Properties:
            Path: /drive/file-services/{id}/soft-delete
            Method: DELETE



  RestoreFileFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub restoreFile-${Environment}
      CodeUri: lambda/restoreFile/
      Handler: index.handler
      Runtime: nodejs18.x
      Policies:
      - Statement:
          - Effect: Allow
            Action:
              - s3:ListObjectVersions     # find the delete marker
              - s3:DeleteObjectVersion    # remove the delete marker to restore
            Resource:
              - !Sub "${DriveBucket.Arn}/*"
          - Effect: Allow
            Action:
              - dynamodb:UpdateItem
            Resource: !GetAtt DriveTable.Arn
      Environment:
        Variables:
          DRIVE_BUCKET: !Ref DriveBucket
          DRIVE_TABLE: !Ref DriveTable
      Events:
        RestoreFile:
          Type: Api
          Properties:
            RestApiId: !Ref DriveApi
            Path: /drive/file-services/{id}/restore
            Method: POST

 
  ScanProcessorFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub scanProcessor-${Environment}
      CodeUri: lambda/scanProcessor/
      Handler: index.handler
      Runtime: nodejs18.x
      Timeout: 900
      Policies:
      - Statement:
          # --- SQS ---
          - Effect: Allow
            Action:
              - sqs:ReceiveMessage
              - sqs:DeleteMessage
              - sqs:GetQueueAttributes
            Resource: !GetAtt ScanQueue.Arn

          # --- S3: read object to scan ---
          - Effect: Allow
            Action:
              - s3:GetObject
              - s3:DeleteObject  # once processed, remove from unscanned
            Resource: !Sub arn:aws:s3:::${DriveUnscannedBucket}/*

          # --- S3: write to clean bucket ---
          - Effect: Allow
            Action:
              - s3:PutObject
            Resource: !Sub arn:aws:s3:::${DriveBucket}/*

          # --- S3: write to quarantined bucket ---
          - Effect: Allow
            Action:
              - s3:PutObject
            Resource: !Sub arn:aws:s3:::${DriveQuarantinedBucket}/*

          # --- DynamoDB: update scan and drive status ---
          - Effect: Allow
            Action:
              - dynamodb:UpdateItem
              - dynamodb:GetItem
              - dynamodb:PutItem
            Resource:
              - !GetAtt ScanTable.Arn
              - !GetAtt DriveTable.Arn

          # --- Optional if using Step Functions orchestration ---
          - Effect: Allow
            Action:
              - states:StartExecution
            Resource: "*"
            Condition:
              StringLikeIfExists:
                "aws:CalledVia": "lambda.amazonaws.com"

      
      Environment:
        Variables:
          DRIVE_UNSCANNED_BUCKET: !Ref DriveUnscannedBucket
          DRIVE_BUCKET: !Ref DriveBucket
          DRIVE_QUARANTINED_BUCKET: !Ref DriveQuarantinedBucket
          SCAN_TABLE: !Ref ScanTable
          DRIVE_TABLE: !Ref DriveTable
      Events:
        ScanQueueEvent:
          Type: SQS
          Properties:
            Queue: !GetArn ScanQueue
            BatchSize: 20


# create a step-function to orchestrate scanning process 

  CleanupWorkerFunction:
  Type: AWS::Serverless::Function
  Properties:
    FunctionName: !Sub cleanupWorker-${Environment}
    CodeUri: lambda/cleanupWorker/
    Handler: index.handler
    Runtime: nodejs18.x
    Timeout: 300
    MemorySize: 512
    Policies:
      - Version: "2012-10-17"
        Statement:
          # S3: read and delete objects only
          - Effect: Allow
            Action:
              - s3:ListBucket
            Resource: !Ref DriveBucket
          - Effect: Allow
            Action:
              - s3:GetObject
              - s3:DeleteObject
            Resource: !Sub arn:aws:s3:::${DriveBucket}/*
          # DynamoDB: read and delete items only
          - Effect: Allow
            Action:
              - dynamodb:GetItem
              - dynamodb:Query
              - dynamodb:DeleteItem
            Resource: !GetAtt DriveTable.Arn
    Environment:
      Variables:
        DRIVE_BUCKET: !Ref DriveBucket
        DRIVE_TABLE: !Ref DriveTable
    Events:
      DailyCleanup:
        Type: Schedule
        Properties:
          Schedule: rate(1 hour)

  # S3 Event Notifications
  UnscannedBucketNotification:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref DriveUnscannedBucket
      NotificationConfiguration:
        QueueConfigurations:
          - Event: s3:ObjectCreated:*
            Queue: !GetArn ScanQueue

# SQS queue policy to allow the bucket to send messages
ScanQueuePolicy:
  Type: AWS::SQS::QueuePolicy
  Properties:
    Queues:
      - !Ref ScanQueue
    PolicyDocument:
      Version: "2012-10-17"
      Statement:
        - Effect: Allow
          Principal: "*"
          Action: sqs:SendMessage
          Resource: !GetAtt ScanQueue.Arn
          Condition:
            ArnEquals:
              aws:SourceArn: !Ref DriveUnscannedBucket


  # Cognito User Pool
  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Sub drive-user-pool-${Environment}
      UsernameAttributes:
        - email
      AutoVerifiedAttributes:
        - email

  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId: !Ref UserPool
      ClientName: !Sub drive-client-${Environment}
      GenerateSecret: false
      ExplicitAuthFlows:
        - ALLOW_USER_SRP_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH

Outputs:
  ApiUrl:
    Description: Drive API URL
    Value: !Sub https://${DriveApi}.execute-api.${AWS::Region}.amazonaws.com/${Environment}
  
  UserPoolId:
    Description: Cognito User Pool ID
    Value: !Ref UserPool
  
  UserPoolClientId:
    Description: Cognito User Pool Client ID
    Value: !Ref UserPoolClient
  
  DriveBucketName:
    Description: Main Drive Bucket Name
    Value: !Ref DriveBucket