
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Modular SAM template for Drive & Notes with outputs

Parameters:
  Environment:
    Type: String
    Default: dev

Resources:


  ###########################################################################
  # SHARED LAYERS
  ###########################################################################

  SharedLayers:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: modules/shared/layers.yaml
      Parameters:
        Environment: !Ref Environment


  ###########################################################################
  # DRIVE MODULES
  ###########################################################################

  DriveBuckets:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: modules/drive/buckets.yaml
      Parameters:
        Environment: !Ref Environment


  DriveDynamoDB:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: modules/drive/dynamodb.yaml
      Parameters:
        Environment: !Ref Environment

  DriveLambdas:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: modules/drive/lambdas.yaml
      Parameters:
        Environment: !Ref Environment

  DriveBackground:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: modules/drive/background.yaml
      Parameters:
        Environment: !Ref Environment

  DriveQueue:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: modules/drive/queue.yaml
      Parameters:
        Environment: !Ref Environment


  ###########################################################################
  # NOTES MODULE
  ###########################################################################

  NotesResources:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: modules/notes/notes.yaml
      Parameters:
        Environment: !Ref Environment



Outputs:

  ###########################################################################
  # DRIVE BUCKETS
  ###########################################################################

  DriveBucketName:
    Description: Name of the Drive bucket
    Value: !ImportValue
      Fn::Sub: "drive-bucket-name-${Environment}"

  DriveUnscannedBucketName:
    Description: Name of the Drive unscanned bucket
    Value: !ImportValue
      Fn::Sub: "drive-unscanned-bucket-name-${Environment}"

  DriveQuarantinedBucketName:
    Description: Name of the Drive quarantined bucket
    Value: !ImportValue
      Fn::Sub: "drive-quarantined-bucket-name-${Environment}"

  ###########################################################################
  # DRIVE TABLES
  ###########################################################################

  DriveTableName:
    Description: Name of the Drive DynamoDB table
    Value: !ImportValue
      Fn::Sub: "drive-table-name-${Environment}"

  ScanTableName:
    Description: Name of the Scan DynamoDB table
    Value: !ImportValue
      Fn::Sub: "scan-table-name-${Environment}"

  UserSettingsTableName:
    Description: DynamoDB table for user settings
    Value: !ImportValue
      Fn::Sub: "user-settings-table-name-${Environment}"

  ShareTableName:
    Description: DynamoDB table for share records
    Value: !ImportValue
      Fn::Sub: "share-table-name-${Environment}"

  ###########################################################################
  # NOTES TABLE
  ###########################################################################

  NotesTableName:
    Description: DynamoDB table for notes
    Value: !ImportValue
      Fn::Sub: "notes-table-name-${Environment}"

  ###########################################################################
  # SQS
  ###########################################################################

  ScanQueueUrl:
    Description: URL of SQS queue used for scanning
    Value: !ImportValue
      Fn::Sub: "scan-queue-url-${Environment}"

  ScanQueueArn:
    Description: ARN of SQS queue used for scanning
    Value: !ImportValue
      Fn::Sub: "scan-queue-arn-${Environment}"

  ###########################################################################
  # SHARED LAYER
  ###########################################################################

  AwsSdkV3LayerArn:
    Description: ARN of the AWS SDK v3 Layer
    Value: !ImportValue
      Fn::Sub: "aws-sdk-v3-layer-${Environment}"
