AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  Environment:
    Type: String
    Default: dev

Resources:

  StarageApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref Environment
      Name: !Sub "starage-backend-${Environment}"
      Cors:
        AllowMethods: "'*'"
        AllowHeaders: "'*'"
        AllowOrigin: "'*'"

  ###########################################################################
  # LAYERS
  ###########################################################################

  AwsSdkV3Layer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: !Sub aws-sdk-v3-${Environment}
      Description: AWS SDK v3 for DynamoDB operations
      ContentUri: ../../layers/aws-sdk-v3-layer/
      CompatibleRuntimes:
        - nodejs18.x
      RetentionPolicy: Retain


  ###########################################################################
  # DYNAMODB TABLES
  ###########################################################################

  UserSettingsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub user-settings-${Environment}
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: user_id
          AttributeType: S
        - AttributeName: plan_type
          AttributeType: S
        - AttributeName: quota_reset_at
          AttributeType: 'N'
      KeySchema:
        - AttributeName: user_id
          KeyType: HASH
      TimeToLiveSpecification:
        AttributeName: quota_reset_at
        Enabled: true
      GlobalSecondaryIndexes:
        - IndexName: PlanTypeIndex
          KeySchema:
            - AttributeName: plan_type
              KeyType: HASH
          Projection:
            ProjectionType: ALL
        - IndexName: QuotaResetIndex
          KeySchema:
            - AttributeName: quota_reset_at
              KeyType: HASH
          Projection:
            ProjectionType: KEYS_ONLY
      Tags:
        - Key: Project
          Value: Starage
        - Key: Purpose
          Value: UserSettings

  NotesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub Starage-App-Notes-${Environment}
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
        - AttributeName: noteId
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
        - AttributeName: noteId
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST

  ###########################################################################
  # NOTES FUNCTIONS
  ###########################################################################

  SyncNoteFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub notes-sync-${Environment}
      CodeUri: notes/lambda/sync-notes/
      Handler: index.handler
      Runtime: nodejs18.x
      Layers:
        - !Ref AwsSdkV3Layer
      Environment:
        Variables:
          NOTES_TABLE: !Ref NotesTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref NotesTable
      Events:
        Api:
          Type: Api
          Properties:
            Path: /notes/sync
            Method: post

  GetNotesFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub notes-get-${Environment}
      CodeUri: notes/lambda/get-notes/
      Handler: index.handler
      Runtime: nodejs18.x
      Layers:
        - !Ref AwsSdkV3Layer
      Environment:
        Variables:
          NOTES_TABLE: !Ref NotesTable
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref NotesTable
      Events:
        Api:
          Type: Api
          Properties:
            Path: /notes
            Method: get

  DeleteNoteFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub notes-delete-${Environment}
      CodeUri: notes/lambda/delete-notes/
      Handler: index.handler
      Runtime: nodejs18.x
      Layers:
        - !Ref AwsSdkV3Layer
      Environment:
        Variables:
          NOTES_TABLE: !Ref NotesTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref NotesTable
      Events:
        Api:
          Type: Api
          Properties:
            Path: /notes/{id}
            Method: delete

  RestoreNoteFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub notes-restore-${Environment}
      CodeUri: notes/lambda/restore-notes/
      Handler: index.handler
      Runtime: nodejs18.x
      Layers:
        - !Ref AwsSdkV3Layer
      Environment:
        Variables:
          NOTES_TABLE: !Ref NotesTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref NotesTable
      Events:
        Api:
          Type: Api
          Properties:
            Path: /notes/{id}/restore
            Method: post

  CleanupNotesFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub notes-cleanup-${Environment}
      CodeUri: notes/lambda/cleanup-notes/
      Handler: index.handler
      Runtime: nodejs18.x
      Layers:
        - !Ref AwsSdkV3Layer
      Environment:
        Variables:
          NOTES_TABLE: !Ref NotesTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref NotesTable
      Events:
        DailyCleanup:
          Type: Schedule
          Properties:
            Schedule: rate(1 day)

 
 
  ###########################################################################
  # OUTPUTS
  ###########################################################################

Outputs:

 
  UserSettingsTableName:
    Description: DynamoDB table for user settings
    Value: !Ref UserSettingsTable
    Export:
      Name: !Sub user-settings-table-name-${Environment}

 
  NotesTableName:
    Description: DynamoDB table for notes
    Value: !Ref NotesTable
    Export:
      Name: !Sub notes-table-name-${Environment}

  AwsSdkV3LayerArn:
    Description: ARN of the AWS SDK v3 Layer
    Value: !Ref AwsSdkV3Layer
    Export:
      Name: !Sub aws-sdk-v3-layer-${Environment}